### ISSUE TITLE
Licence compliance (automated if possible)

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk-contrib#162]
Fossa has identified [license issues](https://app.fossa.com/projects/git%2Bgithub.com%2Fopen-feature%2Fgo-sdk-contrib/refs/branch/main/8ee4c520f9efdf42bc2dc715523adc0b1cf7d76b/issues/licensing?page=1&count=20&sort=created_at_desc&status=active&filter%5Btype%5D%5B0%5D=policy_flag&revisionScanId=38217278) with this repo. The only requirement I can see is a requirement to include licenses.

Most are Mozilla. We need to add declarations for these. It seems like we may be able to automate this using: https://github.com/google/go-licenses. We should do this within each module.

**Comment by Kavindu-Dodan** [comment]
I will work on this and similar to the approach taken for flagd [1], let's start by bundling dependency license to release artifacts 

[1] - https://github.com/open-feature/flagd/issues/581
