### ISSUE TITLE
Set span error state for otel error hook

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/go-sdk-contrib#204]
The current OpenFeature hook implementation of otel supports OF error hook [1]. While the implementation record the error, it does not set the span status [2] to error.

From OTEL spec point of view, it is a recommended practice to set the error state when recording an error [3]

> It is highly recommended that you also set a span’s status to Error when using RecordError, unless you do not wish to consider the span tracking a failed operation as an error span. The RecordError function does not automatically set a span status when called.

Consider diff of Jaeger Span views for non-error (current) & error (proposed) 

- non-error (current)

<img width="649" alt="image" src="https://github.com/open-feature/go-sdk-contrib/assets/8186721/d6880fd7-6529-47e8-8064-4f1b27b41961">

- error (proposed)

<img width="637" alt="image" src="https://github.com/open-feature/go-sdk-contrib/assets/8186721/0f68b717-e497-4771-a8f6-cec4c48ba073">

Q : Should we consider a failed flag evaluation to be an error Span ? 

[1] - https://github.com/open-feature/go-sdk-contrib/blob/main/hooks/open-telemetry/pkg/otel.go#L39-L41
[2] - https://opentelemetry.io/docs/concepts/signals/traces/#span-status 
[3] - https://opentelemetry.io/docs/instrumentation/go/manual/#record-errors

**Comment by toddbaert** [comment]
This seems like a bug to me. Is there an equivalent issue in other languages' hooks implementation?

**Comment by Kavindu-Dodan** [comment]
> This seems like a bug to me. Is there an equivalent issue in other languages' hooks implementation?

No, I was playing with Go sdk and came across this :) 

If we agree on this change (setting span state to Error), I can create issues and track the implementation change for this - it's a simple change
