### ISSUE TITLE
[flagd-provider] add events support 

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk-contrib#212]
Once the go-sdk has `events` and `init/shutdown` support, we need to update the flagd-provider to emit events and do proper init/shutdown. We already have a stream implemented for cache-busing, so this should be pretty simple.

Definition of done:
- flagd does does startup logic (like initializing it's stream) in `initialize` function
- flagd shuts down stream in `close/shutdown` function
- flagd emits appropriate events on flag changes, and errors
- uses conformant defaults (defaults to 0 (infinite) connection retries), see [here](https://github.com/open-feature/flagd/blob/main/docs/other_resources/creating_providers.md#environment-variables)
- associated testing

**Comment by toddbaert** [comment]
@oxddr I'm really sorry! this issue was resolved by @Kavindu-Dodan [here](https://github.com/open-feature/go-sdk-contrib/pull/317).

If it's primarily Go you're interested in, you might want to keep an eye on the  issues in the [flagd repo](https://github.com/open-feature/flagd/issues) as well. You could also write your own [provider](https://openfeature.dev/specification/sections/providers), and add it here if you can think of a feature-flag source that would be generally useful to people!

**Comment by oxddr** [comment]
No worries. I am going to keep an eye on open on issues around flagd (yes, contributions in Go are my primarily interest).
