### ISSUE TITLE
[otel hooks] add functional means of adding custom attributes to metrics and tracing hooks

### ISSUE THREAD

**Issue by toddbaert** [open-feature/go-sdk-contrib#294]
Currently it's possible to map flag metadata values to custom OTel attributes (see [here](https://github.com/open-feature/go-sdk-contrib/tree/main/hooks/open-telemetry#withflagmetadatadimensions)). However this approach has limitations, as it can only map values 1:1.

We should implement something similar to the [JS implementation](https://github.com/open-feature/js-sdk-contrib/tree/main/libs/hooks/open-telemetry#custom-metric-attributes), which allows consumers to provide a function that takes the flag metadata and returns OTel attributes.

We should add the same functionality to the Tracing hook.

**Comment by craigpastro** [comment]
Hi @toddbaert. I can try giving this a shot if that is okay?

**Comment by Kavindu-Dodan** [comment]
@craigpastro than you for the interest 🙌 

However, I already attempted this - https://github.com/open-feature/go-sdk-contrib/pull/311 Sorry for not referencing this in the PR 😞

**Comment by craigpastro** [comment]
Oh, whoops. I should have looked at the open PRs.
