### ISSUE TITLE
Add Contributing Doc

### ISSUE THREAD

**Issue by beeme1mr** [open-feature/go-sdk-contrib#30]
## Summary

Add a contributing document to the root of the repo. People interested in contributing for the first time can use this document to understand how they should get started. For a basic example, please refer to the [contributing docs in the js contrib repo](https://github.com/open-feature/js-sdk-contrib/blob/main/CONTRIBUTING.md).

**Comment by Sindhuinti** [comment]
Hey @beeme1mr I would like to work on this project.
