### ISSUE TITLE
[Flagd] offline mode for in-process provider 

### ISSUE THREAD

**Issue by Kavindu-Dodan** [open-feature/go-sdk-contrib#375]
Flagd has in-process evaluation capability introduced through PR https://github.com/open-feature/go-sdk-contrib/pull/327 

Similar to the **offline** in-process mode in Java provider [^1], we should introduce an offline in-process mode for Go provider. 

This needs to be followed up after completing the #393

[^1]: - https://github.com/open-feature/java-sdk-contrib/pull/473

**Comment by thisthat** [comment]
We should also include the improvement done in https://github.com/open-feature/java-sdk-contrib/pull/614
This would enable mounting a ConfigMap directly on a Pod that contains the FF definition.

**Comment by Kavindu-Dodan** [comment]
> We should also include the improvement done in [open-feature/java-sdk-contrib#614](https://github.com/open-feature/java-sdk-contrib/pull/614) This would enable mounting a ConfigMap directly on a Pod that contains the FF definition.

Opened PR #421 and in that I use flagd's implemenation of the file sync. This has proven to work fine (compared to what I found on Java libraries and watchers). I think reusing this reduce complexity and avoid code duplication :)
