### ISSUE TITLE
[ci] Configure renovate 

### ISSUE THREAD

**Issue by james-milligan** [open-feature/go-sdk-contrib#74]
Dependencies are not currently being autoupdated, this is required to conform with the [repository requirements](https://github.com/open-feature/.github/blob/main/CONTRIBUTING.md#repository-requirements)

Renovate can be used to manage the dependencies, and is currently being used in the `js-sdk-contrib` repo and `flagd`.

It may be worthwhile using a custom schedule to reduce the number of PRs that are opened, as all GitHub actions will rerun for each, and as the library of `providers` and `hooks` grow, so will the number of renovate PRs

https://github.com/apps/renovate

**Comment by toddbaert** [comment]
This is done.
